### ISSUE TITLE
no method named `start_async_task` found for struct `godot::prelude::Gd<godot::prelude::Node>` in the current scope (And others)

### ISSUE THREAD

**Issue by kz-n** [Houtamelo/gdext_coroutines#1]
I'm trying to set up the library, i must've gotten something wrong but im not sure what.. 
This is my cargo.toml:
```
[package]
name = "NyquistRS"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[dependencies]
nyquist_lib = { path = "nyquist_lib/" }
cpal = "0.15.3"
kira = { version = "0.9.3", features = ["cpal"] }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
] }
gdext_coroutines = { version = "0.4.0", features = ["async"] }
smol = "2.0.0"
```

and to try out the lib i copied and pasted this code https://github.com/Houtamelo/gdext_coroutines/blob/main/rust/integration_tests/src/lib.rs

doesnt build stating those errors

**Comment by Houtamelo** [comment]
Hello, could you share the code snippet that's emitting those errors?

Do you have the gdext_coroutines types imported? (eg: `use gdext_coroutines::prelude::*:`)

**Comment by kz-n** [comment]
I tried to write my own code and it had those errors so I then tried to copy paste one of the examples i found at https://github.com/Houtamelo/gdext_coroutines/blob/main/rust/integration_tests/src/lib.rs , the error is present when trying to build that file for me

**Comment by Houtamelo** [comment]
Where you using the version 0.3 previously? If so, it's possible that the dependency wasn't updated yet.
You can run cargo update to fix that. 

The code in the integration_tests folder does compile here and I did run the tests manually.

Also, could you paste the entire error message? As well as the code snippet that caused the errors.

**Comment by kz-n** [comment]
So I tried to do a short snippet to replicate the issue, and I think i ended up getting another one,
This is the code:
```rs
#![feature(coroutines)]
#![feature(coroutine_trait)]
#![feature(stmt_expr_attributes)]
#![feature(unboxed_closures)]
use gdext_coroutines::prelude::*;
use godot::prelude::*;

#[derive(GodotClass)]
#[class(base=Node)]
struct PlaybackManagerRS {}

#[godot_api]
impl INode for PlaybackManagerRS {
    fn init(base: Base<Node>) -> Self {
        Self {}
    }
}
#[godot_api]
impl PlaybackManagerRS {
    #[func]
    fn test(&self) {
        self.start_async_task(async {})
    }
}
```

And here's the error
```
   Compiling NyquistRS v0.1.0 (/run/media/kz-n/Games/github/NyquistRS/rust)
error[E0599]: the method `start_async_task` exists for reference `&PlaybackManagerRS`, but its trait bounds were not satisfied
   --> src/lib.rs:22:14
    |
10  | struct PlaybackManagerRS {}
    | ------------------------ doesn't satisfy `_: GodotClass` or `_: WithBaseField`
...
22  |         self.start_async_task(async {})
    |              ^^^^^^^^^^^^^^^^ method cannot be called on `&PlaybackManagerRS` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `PlaybackManagerRS: godot_core::obj::traits::WithBaseField`
            which is required by `&PlaybackManagerRS: gdext_coroutines::prelude::StartAsyncTask`
            `PlaybackManagerRS: godot_core::obj::traits::GodotClass`
            which is required by `&PlaybackManagerRS: gdext_coroutines::prelude::StartAsyncTask`
note: the traits `godot_core::obj::traits::GodotClass` and `godot_core::obj::traits::WithBaseField` must be implemented
   --> /home/kz-n/.cargo/registry/src/index.crates.io-6f17d22bba15001f/godot-core-0.1.3/src/obj/traits.rs:28:1
    |
28  | pub trait GodotClass: Bounds + 'static
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
239 | pub trait WithBaseField: GodotClass + Bounds<Declarer = bounds::DeclUser> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `start_async_task`, perhaps you need to implement it:
            candidate #1: `gdext_coroutines::prelude::StartAsyncTask`

warning: unused import: `gdext_coroutines::prelude`
 --> src/lib.rs:5:5
  |
5 | use gdext_coroutines::prelude::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `base`
  --> src/lib.rs:14:13
   |
14 |     fn init(base: Base<Node>) -> Self {
   |             ^^^^ help: if this is intentional, prefix it with an underscore: `_base`
   |
   = note: `#[warn(unused_variables)]` on by default

For more information about this error, try `rustc --explain E0599`.
warning: `NyquistRS` (lib) generated 2 warnings
error: could not compile `NyquistRS` (lib) due to 1 previous error; 2 warnings emitted
```

**Comment by kz-n** [comment]
> Where you using the version 0.3 previously? If so, it's possible that the dependency wasn't updated yet. You can run cargo update to fix that.
> 
> The code in the integration_tests folder does compile here and I did run the tests manually.
> 
> Also, could you paste the entire error message? As well as the code snippet that caused the errors.

Also no I just tried to use this library, haven't in the past

**Comment by kz-n** [comment]
Ok so I ended up fixing this by adding this to `PlaybackMangerRS`
```rs
#[derive(GodotClass)]
#[class(init, base=Node)]
struct PlaybackManagerRS {
    base: Base<Node>,
}
```

and changing the `godot` version in my toml file from the github link as described in the godot rust book to "0.1"

I'd say skill issue on my end, closed!

**Comment by Houtamelo** [comment]
> So I tried to do a short snippet to replicate the issue, and I think i ended up getting another one, This is the code:
> 
> ```rust
> #![feature(coroutines)]
> #![feature(coroutine_trait)]
> #![feature(stmt_expr_attributes)]
> #![feature(unboxed_closures)]
> use gdext_coroutines::prelude::*;
> use godot::prelude::*;
> 
> #[derive(GodotClass)]
> #[class(base=Node)]
> struct PlaybackManagerRS {}
> 
> #[godot_api]
> impl INode for PlaybackManagerRS {
>     fn init(base: Base<Node>) -> Self {
>         Self {}
>     }
> }
> #[godot_api]
> impl PlaybackManagerRS {
>     #[func]
>     fn test(&self) {
>         self.start_async_task(async {})
>     }
> }
> ```
> 
> And here's the error
> 
> ```
>    Compiling NyquistRS v0.1.0 (/run/media/kz-n/Games/github/NyquistRS/rust)
> error[E0599]: the method `start_async_task` exists for reference `&PlaybackManagerRS`, but its trait bounds were not satisfied
>    --> src/lib.rs:22:14
>     |
> 10  | struct PlaybackManagerRS {}
>     | ------------------------ doesn't satisfy `_: GodotClass` or `_: WithBaseField`
> ...
> 22  |         self.start_async_task(async {})
>     |              ^^^^^^^^^^^^^^^^ method cannot be called on `&PlaybackManagerRS` due to unsatisfied trait bounds
>     |
>     = note: the following trait bounds were not satisfied:
>             `PlaybackManagerRS: godot_core::obj::traits::WithBaseField`
>             which is required by `&PlaybackManagerRS: gdext_coroutines::prelude::StartAsyncTask`
>             `PlaybackManagerRS: godot_core::obj::traits::GodotClass`
>             which is required by `&PlaybackManagerRS: gdext_coroutines::prelude::StartAsyncTask`
> note: the traits `godot_core::obj::traits::GodotClass` and `godot_core::obj::traits::WithBaseField` must be implemented
>    --> /home/kz-n/.cargo/registry/src/index.crates.io-6f17d22bba15001f/godot-core-0.1.3/src/obj/traits.rs:28:1
>     |
> 28  | pub trait GodotClass: Bounds + 'static
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 239 | pub trait WithBaseField: GodotClass + Bounds<Declarer = bounds::DeclUser> {
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: items from traits can only be used if the trait is implemented and in scope
>     = note: the following trait defines an item `start_async_task`, perhaps you need to implement it:
>             candidate #1: `gdext_coroutines::prelude::StartAsyncTask`
> 
> warning: unused import: `gdext_coroutines::prelude`
>  --> src/lib.rs:5:5
>   |
> 5 | use gdext_coroutines::prelude::*;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> warning: unused variable: `base`
>   --> src/lib.rs:14:13
>    |
> 14 |     fn init(base: Base<Node>) -> Self {
>    |             ^^^^ help: if this is intentional, prefix it with an underscore: `_base`
>    |
>    = note: `#[warn(unused_variables)]` on by default
> 
> For more information about this error, try `rustc --explain E0599`.
> warning: `NyquistRS` (lib) generated 2 warnings
> error: could not compile `NyquistRS` (lib) due to 1 previous error; 2 warnings emitted
> ```

I should have mentioned in the documentation that this only works for types that have an explicit `Base` field, my bad!

> and changing the godot version in my toml file from the github link as described in the godot rust book to "0.1"

Which version were you using before? It should be compatible with all gdext versions released so far.

**Comment by kz-n** [comment]
I'm not sure, i was just using the latest commit available (as thats what i got instructed to do by the gdext book)
```toml
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
] }
```
