### ISSUE TITLE
suggestion: add delta_time to keep_waiting

### ISSUE THREAD

**Issue by 0x53A** [Houtamelo/gdext_coroutines#3]
Hi, I started playing with godot rust and found your coroutine lib extremely useful!

I wanted to animate a node from a coroutine, that is, wait one frame each then change it's position.
For that I needed access to the elapsed delta.

I've patched that in, in a fork: https://github.com/Houtamelo/gdext_coroutines/commit/0471d56349ee9aa12f1449a10ab87de4e4b4b68b

I'm then using it like this:

```rust
struct WaitForFramesWithDelta {
    frames_to_wait: u32,
    delta: Arc<Cell<f64>>,
    first: bool
}

impl KeepWaiting for WaitForFramesWithDelta {
    fn keep_waiting(&mut self, delta_time: f64) -> bool {
        let do_keep_waiting = self.frames_to_wait != 0;
        self.frames_to_wait = self.frames_to_wait.saturating_sub(1);

        if !self.first {
            self.delta.update(|d| d + delta_time);
        } else {
            self.first = false;
        }
        return do_keep_waiting;
    }
}

fn wait_for_frames_with_delta(frames_to_wait: u32, delta: &Arc<Cell<f64>>) -> Yield {
    return Yield::Dyn(Box::new(WaitForFramesWithDelta { frames_to_wait: frames_to_wait, delta: delta.clone(), first: true }));
}


fn foo() {
    // ...
    let delta_arc = Arc::new(Cell::new(0.0));
    yield wait_for_frames_with_delta(1, &delta_arc);
     let delta: f64 = delta_arc.get();
  // ...
}
```

as I understand it, ``keep_waiting`` is called immediatly on a yield point, so when accumulating the elapsed delta, I have to ignore the first call.

----

What do you think? Technically it would be a breaking change, since the trait signature changes.

**Comment by Houtamelo** [comment]
I would like to merge your change, I made a comment in your PR: https://github.com/Houtamelo/gdext_coroutines/pull/4

**Comment by Houtamelo** [comment]
Closed by https://github.com/Houtamelo/gdext_coroutines/commit/41fafbd58fb6694f42b67b1c2794461fed52aee3

@0x53A Btw, have you checked https://github.com/Houtamelo/spire_tween ? I made it specifically for procedural animations which might fit your use case.

**Comment by 0x53A** [comment]
> Btw, have you checked https://github.com/Houtamelo/spire_tween ?

not yet, I'll take a look!
